default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["MAISON_PARFUM_DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: maison_parfum_development

test:
  <<: *default
  database: maison_parfum_test

production:
  <<: *default
  database: maison_parfum_production
  username: maison_parfum
  password: <%= ENV["MAISON_PARFUM_DATABASE_PASSWORD"] %>